### PR TITLE
Adds Chef Recipe YAML support with language and snippets

### PR DESCRIPTION
**Pull request by collinmcneese**
Signed-off-by: Collin McNeese <cmcneese@chef.io>

## Description
\
Introduces support for Chef Infra Recipes in YAML format.

* Adds language `chef_recipe_yaml` which includes scope from base `YAML` language.
* Matches to apply `chef_recipe_yaml` language only to `yml` and `yaml` files which exist under pattern `**/recipes/` to not conflict with other `YAML` file types that a developer might work with.
* Adds snippets for `YAML` recipe configurations with auto-completion for `chef_recipe_yaml` language files.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [X] I have read the **CONTRIBUTING** document.
- [X] I have run the pre-merge tests locally and they pass.
- [X] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [X] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by kmf** [comment]
How are these snippets generated?

**Comment by collinmcneese** [comment]
> How are these snippets generated?

The `chef_yaml_resources.json` contents were generated manually based on `chef_resources.json`, which is also generated 
 and maintained manually.  Ideally this should be a scripted process but for now that is how they were created.

**Comment by collinmcneese** [comment]
image
This is a sample of what the yaml snippets look like

**Comment by kmf** [comment]
@collinmcneese I've built similar snippets for Vim, I'm scrapping docs to do it.
there should be an easier way to implement this for all editors.

Maybe I can reach out to someone on the docs team

https://github.com/kmf/vim-chef-snippets#how-is-this-built

**Comment by collinmcneese** [comment]
> @collinmcneese I've built similar snippets for Vim, I'm scrapping docs to do it.
> there should be an easier way to implement this for all editors.
> 
> Maybe I can reach out to someone on the docs team
> 
> https://github.com/kmf/vim-chef-snippets#how-is-this-built

I like that approach, seems to work well.  I'll put what I've mocked up based on that as a different PR in to this repo to add additional tasks on the autogenerate Rake to handle the Ruby and YAML outputs on these so that way they don't have to be manual ongoing

**Pull request merged**
